-- MySQL Script generated by MySQL Workbench
-- Thu Nov  1 19:22:21 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hr_app_db_v2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hr_app_db_v2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hr_app_db_v2` DEFAULT CHARACTER SET utf8 ;
USE `hr_app_db_v2` ;

-- -----------------------------------------------------
-- Table `hr_app_db_v2`.`candidate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hr_app_db_v2`.`candidate` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `surname` VARCHAR(100) NULL DEFAULT NULL,
  `birthday` DATE NULL DEFAULT NULL,
  `salary` DECIMAL(10,2) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hr_app_db_v2`.`skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hr_app_db_v2`.`skill` (
  `skill` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`skill`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hr_app_db_v2`.`candidatecompitance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hr_app_db_v2`.`candidatecompitance` (
  `idCandidate` BIGINT(20) UNSIGNED NOT NULL,
  `skill` VARCHAR(50) NOT NULL,
  INDEX `fk_candidatecompitance_candidate1_idx` (`idCandidate` ASC),
  PRIMARY KEY (`idCandidate`, `skill`),
  CONSTRAINT `fk_candidatecompitance_candidate1`
    FOREIGN KEY (`idCandidate`)
    REFERENCES `hr_app_db_v2`.`candidate` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_candidatecompitance_skill1`
    FOREIGN KEY (`skill`)
    REFERENCES `hr_app_db_v2`.`skill` (`skill`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hr_app_db_v2`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hr_app_db_v2`.`users` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `surname` VARCHAR(100) NULL DEFAULT NULL,
  `userState` ENUM('Active', 'Blocked') NOT NULL DEFAULT 'Active',
  `isAdmin` ENUM('Admin', 'User') NOT NULL DEFAULT 'User',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hr_app_db_v2`.`vacancy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hr_app_db_v2`.`vacancy` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `idDeveloper` BIGINT(20) UNSIGNED NOT NULL,
  `position` VARCHAR(1000) NOT NULL,
  `salaryFrom` DECIMAL(10,2) UNSIGNED NOT NULL,
  `salaryTo` DECIMAL(10,2) NULL DEFAULT NULL,
  `vacancyState` ENUM('Active', 'Closed') NOT NULL,
  `experienceYearsRequire` DECIMAL(10,2) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vacancy_users1_idx` (`idDeveloper` ASC),
  CONSTRAINT `idDeveloper`
    FOREIGN KEY (`idDeveloper`)
    REFERENCES `hr_app_db_v2`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hr_app_db_v2`.`interview`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hr_app_db_v2`.`interview` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `idVacancy` BIGINT(20) UNSIGNED NOT NULL,
  `idCandidate` BIGINT(20) UNSIGNED NOT NULL,
  `planDate` DATETIME NOT NULL,
  `factDate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_interview_candidate1_idx` (`idCandidate` ASC),
  INDEX `fk_interview_vacancy1_idx` (`idVacancy` ASC),
  CONSTRAINT `fk_interview_candidate1`
    FOREIGN KEY (`idCandidate`)
    REFERENCES `hr_app_db_v2`.`candidate` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_interview_vacancy1`
    FOREIGN KEY (`idVacancy`)
    REFERENCES `hr_app_db_v2`.`vacancy` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hr_app_db_v2`.`interviewfeedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hr_app_db_v2`.`interviewfeedback` (
  `feedbackId` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `idInterview` BIGINT(20) UNSIGNED NOT NULL,
  `idInterviewer` BIGINT(20) UNSIGNED NOT NULL,
  `feedbackState` ENUM('JobOffer', 'NonJobOffer') NOT NULL,
  `reason` VARCHAR(2000) NOT NULL,
  INDEX `fk_interviewfeedback_interview1_idx` (`idInterview` ASC),
  INDEX `fk_interviewfeedback_users1_idx` (`idInterviewer` ASC),
  PRIMARY KEY (`feedbackId`),
  CONSTRAINT `fk_interviewfeedback_interview1`
    FOREIGN KEY (`idInterview`)
    REFERENCES `hr_app_db_v2`.`interview` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_interviewfeedback_users1`
    FOREIGN KEY (`idInterviewer`)
    REFERENCES `hr_app_db_v2`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hr_app_db_v2`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hr_app_db_v2`.`role` (
  `role` VARCHAR(50) NOT NULL,
  UNIQUE INDEX `role` (`role` ASC),
  PRIMARY KEY (`role`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hr_app_db_v2`.`userroles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hr_app_db_v2`.`userroles` (
  `idUser` BIGINT(20) UNSIGNED NOT NULL,
  `role` VARCHAR(50) NOT NULL,
  INDEX `idUser_idx` (`idUser` ASC),
  PRIMARY KEY (`role`, `idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC),
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `hr_app_db_v2`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_userroles_role1`
    FOREIGN KEY (`role`)
    REFERENCES `hr_app_db_v2`.`role` (`role`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hr_app_db_v2`.`vacancycandidate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hr_app_db_v2`.`vacancycandidate` (
  `vacancycandidateId` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `vacancy_id` BIGINT(20) UNSIGNED NOT NULL,
  `idCandidate` BIGINT(20) UNSIGNED NOT NULL,
  `suitableState` ENUM('Suit', 'NonSuit') NOT NULL,
  `reason` VARCHAR(1000) NOT NULL,
  INDEX `fk_vacancycandidate_candidate1_idx` (`idCandidate` ASC),
  PRIMARY KEY (`vacancycandidateId`),
  CONSTRAINT `fk_vacancycandidate_candidate1`
    FOREIGN KEY (`idCandidate`)
    REFERENCES `hr_app_db_v2`.`candidate` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_vacancycandidate_vacancy1`
    FOREIGN KEY (`vacancy_id`)
    REFERENCES `hr_app_db_v2`.`vacancy` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hr_app_db_v2`.`vacancyrequirement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hr_app_db_v2`.`vacancyrequirement` (
  `idVacancy` BIGINT(20) UNSIGNED NOT NULL,
  `skill` VARCHAR(50) NOT NULL,
  INDEX `fk_vacancyrequirement_vacancy1_idx` (`idVacancy` ASC),
  PRIMARY KEY (`skill`, `idVacancy`),
  CONSTRAINT `fk_vacancyrequirement_vacancy1`
    FOREIGN KEY (`idVacancy`)
    REFERENCES `hr_app_db_v2`.`vacancy` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_vacancyrequirement_skill1`
    FOREIGN KEY (`skill`)
    REFERENCES `hr_app_db_v2`.`skill` (`skill`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hr_app_db_v2`.`ContactDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hr_app_db_v2`.`ContactDetails` (
  `contactId` BIGINT(20) UNSIGNED NOT NULL,
  `idCandidate` BIGINT(20) UNSIGNED NOT NULL,
  `contactType` ENUM('Email', 'Phone', 'Skype') NULL,
  `ContactDetails` VARCHAR(500) NOT NULL,
  INDEX `fk_ContactDetails_candidate1_idx` (`idCandidate` ASC),
  PRIMARY KEY (`contactId`),
  CONSTRAINT `fk_ContactDetails_candidate1`
    FOREIGN KEY (`idCandidate`)
    REFERENCES `hr_app_db_v2`.`candidate` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hr_app_db_v2`.`Attachment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hr_app_db_v2`.`Attachment` (
  `attachmentId` BIGINT(20) UNSIGNED NOT NULL,
  `idCandidate` BIGINT(20) UNSIGNED NOT NULL,
  `filePath` VARCHAR(1000) NOT NULL,
  `attachmentType` ENUM('doc', 'pdf', 'txt', 'xlsl', 'other') NOT NULL DEFAULT 'other',
  INDEX `fk_Attachment_candidate1_idx` (`idCandidate` ASC),
  PRIMARY KEY (`attachmentId`),
  CONSTRAINT `fk_Attachment_candidate1`
    FOREIGN KEY (`idCandidate`)
    REFERENCES `hr_app_db_v2`.`candidate` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
